# Site settings
title: gabalese bits and pieces
email: gabriele@alese.it
description: > # this means to ignore newlines until "baseurl:"
  Python web developer in London, wannabe perfectionist with too many deadlines.
  Commited to improve a bit every day, and this blog is part of the 'share back what you've learnt' plan.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gabale.se" # the base hostname & protocol for your site
twitter_username: gabalese
github_username:  gabalese

# Build settings
markdown: kramdown
